# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='用户名')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='学校')),
                ('nativePlace', models.CharField(blank=True, max_length=50, null=True, verbose_name='家乡')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'username',
            },
        ),
    ]
