# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181120_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='head',
            field=models.ImageField(default='images/infortx.png', upload_to='shop/%Y%m', verbose_name='头像'),
        ),
    ]
