# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_username_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='head',
            field=models.ImageField(default='head/oppo.jpg', upload_to='shop/%Y%m', verbose_name='头像'),
        ),
    ]
