# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181123_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='head',
            field=models.ImageField(blank=True, default='head/oppo.jpg', null=True, upload_to='head', verbose_name='头像'),
        ),
    ]
