# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0002_auto_20181127_1707'),
        ('user', '0007_auto_20181123_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('userName', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('telephone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('harea', models.CharField(blank=True, max_length=50, null=True, verbose_name='省')),
                ('hproper', models.CharField(blank=True, max_length=50, null=True, verbose_name='市')),
                ('hcity', models.CharField(max_length=50, verbose_name='区')),
                ('street', models.CharField(max_length=50, verbose_name='街道')),
                ('inDetail', models.CharField(max_length=255, verbose_name='详细描述')),
                ('default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Username', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
                'db_table': 'DeliveryAddress',
            },
        ),
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('orderNum', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('orderPrice', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='订单价格')),
                ('UserName', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('Telephone', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('orderState', models.SmallIntegerField(choices=[(3, '待评价'), (0, '待付款'), (4, '已完成'), (2, '待收货'), (1, '退发货')], default=0, verbose_name='订单状态')),
                ('money', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='实际支付')),
                ('AddressKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderForm.DeliveryAddress', verbose_name='收货地址')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'OrderInformation',
            },
        ),
        migrations.CreateModel(
            name='OrdersGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('goodsNum', models.SmallIntegerField(verbose_name='商品数量')),
                ('goodsPrice', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='商品价格')),
                ('OrderInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderForm.OrderInformation', verbose_name='订单信息')),
                ('goodsSku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Goods', verbose_name='SKU商品')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'OrdersGoods',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('pay', models.CharField(max_length=50, verbose_name='付款名称')),
                ('payImg', models.ImageField(upload_to='Home/%Y%m/%d', verbose_name='支付图片')),
            ],
            options={
                'verbose_name': '付款方式',
                'verbose_name_plural': '付款方式',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='TypeShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('transit', models.CharField(max_length=50, verbose_name='运输名称')),
                ('transitCharge', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='运输价格')),
            ],
            options={
                'verbose_name': '运输方式',
                'verbose_name_plural': '运输方式',
                'db_table': 'TypeShipping',
            },
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='PaymentKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderForm.Payment', verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='UserKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Username', verbose_name='用户ID'),
        ),
    ]
