# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='orderState',
            field=models.SmallIntegerField(choices=[(4, '已完成'), (0, '待付款'), (2, '待收货'), (1, '退发货'), (3, '待评价')], default=0, verbose_name='订单状态'),
        ),
    ]
