# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='transitKey',
            field=models.CharField(default=1, max_length=50, verbose_name='运输方式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='transit_price_Key',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='运输价格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='orderState',
            field=models.SmallIntegerField(choices=[(2, '待收货'), (4, '已完成'), (0, '待付款'), (3, '待评价'), (1, '退发货')], default=0, verbose_name='订单状态'),
        ),
    ]
