# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderForm', '0002_auto_20181127_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Username', verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='orderState',
            field=models.SmallIntegerField(choices=[(2, '待收货'), (1, '退发货'), (4, '已完成'), (3, '待评价'), (0, '待付款')], default=0, verbose_name='订单状态'),
        ),
    ]
