# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderForm', '0005_auto_20181128_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='default',
            field=models.BooleanField(default=False, verbose_name='默认地址'),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='orderState',
            field=models.SmallIntegerField(choices=[(2, '待收货'), (0, '待付款'), (1, '退发货'), (3, '待评价'), (4, '已完成')], default=0, verbose_name='订单状态'),
        ),
    ]
