# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('Activity', models.CharField(max_length=50, verbose_name='首页活动名字')),
                ('Activity_Describe', models.CharField(max_length=255, verbose_name='首页活动名字')),
                ('Activity_Order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('Activity_on_putaway', models.BooleanField(choices=[(1, '上架'), (0, '未上架')], default=1, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '首页活动专区',
                'verbose_name_plural': '首页活动专区',
                'db_table': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('class_name', models.CharField(max_length=50, verbose_name='商品分类名')),
                ('class_intro', models.CharField(max_length=255, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('Goods_spu_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('Goods_spu_intro', models.CharField(max_length=255, verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品spu表',
                'verbose_name_plural': '商品spu表',
                'db_table': 'Create',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Activity')),
            ],
            options={
                'verbose_name': '首页专区活动商品表',
                'verbose_name_plural': '首页专区活动商品表',
                'db_table': 'Division',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('Goods_sku_name', models.CharField(max_length=50, verbose_name='商品信息')),
                ('Goods_sku_intro', models.CharField(max_length=255, verbose_name='商品简介')),
                ('Goods_sku_Price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='商品价格')),
                ('Goods_sku_Num', models.IntegerField(verbose_name='商品简介')),
                ('Goods_sku_Sellnum', models.IntegerField(default=0, verbose_name='销售量')),
                ('Goods_sku_Logo', models.ImageField(upload_to='Goods/%Y%m/%d', verbose_name='logo图片')),
                ('Goods_sku_Is_putaway', models.SmallIntegerField(choices=[(1, '上架'), (2, '未上架')], default=1, verbose_name='上架')),
            ],
            options={
                'verbose_name': '商品sku表',
                'verbose_name_plural': '商品sku表',
                'db_table': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('Home_name', models.CharField(max_length=50, verbose_name='首页名字')),
                ('Home_Imgurl', models.ImageField(upload_to='head', verbose_name='图片地址')),
                ('Home_Linkurl', models.URLField(max_length=50, verbose_name='url地址')),
            ],
            options={
                'verbose_name': '首页活动表',
                'verbose_name_plural': '首页活动表',
                'db_table': 'Home',
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('Goods_Img_url', models.ImageField(upload_to='PhotoAlbum/%Y%m/%d', verbose_name='图片地址')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Goods')),
            ],
            options={
                'verbose_name': '商品相册',
                'verbose_name_plural': '商品相册',
                'db_table': 'PhotoAlbum',
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('Page_name', models.CharField(max_length=50, verbose_name='轮播图名称')),
                ('Page_Imgurl', models.ImageField(upload_to='head', verbose_name='图片地址')),
                ('Page_Order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('Goods_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Goods', verbose_name='商品SKUid')),
            ],
            options={
                'verbose_name': '首页模块',
                'verbose_name_plural': '首页模块',
                'db_table': 'SlideShow',
            },
        ),
        migrations.CreateModel(
            name='Unti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('class_unit', models.CharField(max_length=50, verbose_name='单位名称')),
            ],
            options={
                'verbose_name': '商品单位表',
                'verbose_name_plural': '商品单位表',
                'db_table': 'Unti',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='Goods_sku_Unitinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Unti'),
        ),
        migrations.AddField(
            model_name='goods',
            name='Goods_sku_cate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Class'),
        ),
        migrations.AddField(
            model_name='goods',
            name='Goods_spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Create'),
        ),
        migrations.AddField(
            model_name='division',
            name='Division_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Goods', verbose_name='商品SKUid'),
        ),
    ]
