# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
